###1.Dotplot of 76 cell type marker genes.  
import scanpy as sc
import matplotlib.colors as mcolors
import numpy as np

adata = sc.read("merge_405Samples_Sample_New_500_harmonyPlatForm2000_diff_marker_5.h5ad")

SelGene = [
"CPA1",		
"SLC4A4",		
"LRP2",	"CUBN",	
"UMOD",		
"ATP4B",	"CHIA",	
"ENSSSCG00000033382-MUC5A",
"APOA1",				
"OLFM4",		
"BEST4",	"OTOP2",	
"GNG13",		
"DEFB115",		
"TACSTD2",		
"KRT10",		
"CA2",		
"CLCA1",		
"PIGR",		
"KRT8",		
"AQP2",	"AQP3",	
"S100A2",		
"UPK2",		
"EPCAM",		
"CFTR",		
"SFTPC",	"AGER",	
"FOXJ1",		
"SCGB1A1",		
"PRM1",		
"TOP2A",	"HMGB2",	
"INHA",		
"HSD17B3",		
"CD163",		
"FCER1G",		
"AIF1",		
"SLA-DQB1",	"SLA-DRA",	
"BLNK",		
"CD79A",	"CD79B",	
"JCHAIN",		
"HBB",		
"EPX",		
"RETN",		
"NCR1",		
"NKG7",		
"PPBP",		
"MS4A2",
"ITGA4",		
"CD3D",	"CD2",	
"PECAM1",	"CDH5",			
"CYP17A1",		
"SCN7A",		
"COL11A1",	"COL2A1",	"COL9A1",
"RGS5",		
"ACTA2",	"MYH11",	"MYLK",
"PAX7",		
"MYOG",		
"APOE",	"BGN",	
"DCN",		
"COL1A1",		
"COL1A2",	"COL3A1",	
"GHR",		
"RELN",		
"ADIPOQ",	"PPARG",	
"EZR",		
"MYH7",	"MYL2",	
"ACTN2",	"DES",	
"MBP",		
"NPY",		
"AQP4",		
"CFAP126",		
"RLBP1",		
"SNAP25",		
"CHGB",		
"PDGFRA",		
"GRIA4",		
"GNAO1",		
"DCX"
]

sc.pl.dotplot(adata, SelGene, 'CT76',dendrogram=True,save= '_Atlas_CT76_Markerdend1027.pdf')
sc.pl.matrixplot(adata, SelGene,"CT76",dendrogram=True,colorbar_title="mean z-score",vmin=0,vmax=2,cmap="OrRd", save='_Atlas_CT76_Markerdend1027.pdf')



